--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 01. 25. 8:37:41
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS foci;

CREATE DATABASE IF NOT EXISTS foci
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE foci;

--
-- Create table `csapatok`
--
CREATE TABLE IF NOT EXISTS csapatok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  csapatNev VARCHAR(50) NOT NULL,
  menendzser VARCHAR(50) DEFAULT NULL,
  orszag VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `jatekosok`
--
CREATE TABLE IF NOT EXISTS jatekosok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  jatekosNev VARCHAR(50) NOT NULL,
  csapatId INT(11) DEFAULT NULL,
  pozicio VARCHAR(50) DEFAULT NULL,
  nemzetiseg VARCHAR(50) DEFAULT NULL,
  fizetes DECIMAL(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE jatekosok 
  ADD CONSTRAINT FK_jatekosok_csapatok_id FOREIGN KEY (csapatId)
    REFERENCES csapatok(id);

-- 
-- Dumping data for table csapatok
--
-- Table foci.csapatok does not contain any data (it is empty)

-- 
-- Dumping data for table jatekosok
--
-- Table foci.jatekosok does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;