--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 01. 26. 9:11:42
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS foci;

CREATE DATABASE IF NOT EXISTS foci
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE foci;

--
-- Create table `csapatok`
--
CREATE TABLE IF NOT EXISTS csapatok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  csapatNev VARCHAR(50) NOT NULL,
  menendzser VARCHAR(50) DEFAULT NULL,
  orszag VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 21,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `jatekosok`
--
CREATE TABLE IF NOT EXISTS jatekosok (
  id INT(11) NOT NULL AUTO_INCREMENT,
  jatekosNev VARCHAR(50) NOT NULL,
  csapatId INT(11) DEFAULT NULL,
  pozicio VARCHAR(50) DEFAULT NULL,
  nemzetiseg VARCHAR(50) DEFAULT NULL,
  fizetes DECIMAL(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 301,
AVG_ROW_LENGTH = 273,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE jatekosok 
  ADD CONSTRAINT FK_jatekosok_csapatok_id FOREIGN KEY (csapatId)
    REFERENCES csapatok(id);

-- 
-- Dumping data for table csapatok
--
INSERT INTO csapatok VALUES
(1, 'Real Madrid', 'Carlo Ancelotti', 'Spanyolország'),
(2, 'Manchester City', 'Pep Guardiola', 'Anglia'),
(3, 'Bayern München ', 'Julian Nagelsmann', 'Németország'),
(4, 'Paris Saint-Germain', 'Mauricio Pochettino', 'Franciaország'),
(5, 'Liverpool', 'Jürgen Klopp', 'Anglia'),
(6, 'FC Barcelona', 'Xavi Hernandez', 'Spanyolország'),
(7, 'Juventus', 'Massimiliano Allegri', 'Olaszország'),
(8, 'Manchester United', 'Ralf Rangnick', 'Anglia'),
(9, 'Chelsea', 'Thomas Tuchel', 'Anglia'),
(10, 'Borussia Dortmund', 'Marco Rose', 'Németország'),
(11, 'Inter Milan', 'Simone Inzaghi', 'Olaszország'),
(12, 'Atletico Madrid', 'Diego Simeone', 'Spanyolország'),
(13, 'AC Milan', 'Stefano Pioli', 'Olaszország'),
(14, 'Arsenal', 'Mikel Arteta', 'Anglia'),
(15, 'Ajax', 'Erik ten Hag', 'Hollandia'),
(16, 'RB Leipzig', 'Jesse Marsch', 'Németország'),
(17, 'Sevilla FC', 'Julen Lopetegui', 'Spanyolország'),
(18, 'Napoli', 'Luciano Spalletti', 'Olaszország'),
(19, 'Tottenham Hotspur', 'Antonio Conte', 'Anglia'),
(20, 'AS Roma', 'Jose Mourinho', 'Olaszország');

-- 
-- Dumping data for table jatekosok
--
INSERT INTO jatekosok VALUES
(241, 'Karim Benzema', 1, 'Csatár', 'Francia', 500.00),
(242, 'Luka Modrić', 1, 'Középpályás', 'Horvát', 200.00),
(243, 'Vinícius Júnior', 1, 'Szélső', 'Brazil', 250.00),
(244, 'Kevin De Bruyne', 2, 'Középpályás', 'Belga', 525.00),
(245, 'Raheem Sterling', 2, 'Szélső', 'Angol', 177.00),
(246, 'Ruben Dias', 2, 'Védő ', 'Portugál', 200.10),
(247, 'Robert Lewandowski', 3, 'Csatár', 'Lengyel', 370.00),
(248, 'Joshua Kimmich', 3, 'Középpályás', 'Német', 102.00),
(249, 'Manuel Neuer', 3, 'Kapus', 'Német', 155.00),
(250, 'Kylian Mbappé', 4, 'Csatár', 'Francia', 126.50),
(251, 'Neymar Jr', 4, 'Szélső', 'Brazil', 222.20),
(252, 'Marco Verratt', 4, 'Középpályás', 'Olasz', 103.00),
(253, 'Mohamed Salah', 5, 'Szélső', 'Egyiptomi', 199.00),
(254, 'Virgil van Dijk', 5, 'Védő', 'Holland', 188.00),
(255, 'Sadio Mané', 5, 'Szélső', 'Szenegáli', 100.30),
(256, 'Lionel Messi', 6, 'Szélső', 'Argentin', 0.10),
(257, 'Frenkie de Jong', 6, 'Középpályás', 'Holland', 112.00),
(258, 'Ansu Fati', 6, 'Szélső', 'Spanyol', 211.00),
(259, 'Cristiano Ronaldo', 7, 'Csatár', 'Portugál', 900.00),
(260, 'Paulo Dybala', 7, 'Támadó középpályás', 'Argentin', 214.00),
(261, 'De Ligt', 7, 'Védő', 'Holland', 367.00),
(262, 'Bruno Fernandes', 8, 'Középpályás', 'Portugál', 498.00),
(263, 'Marcus Rashford', 8, 'Szélső', 'Angol', 513.00),
(264, 'Harry Maguire', 8, 'Védő', 'Angol', 655.00),
(265, 'N Golo Kanté', 9, 'Középpályás', 'Francia', 767.00),
(266, 'Mason Mount', 9, 'Középpályás', 'Angol', 868.00),
(267, 'Romelu Lukaku', 9, 'Csatár', 'Belgiumi', 978.00),
(268, 'Erling Haaland', 10, 'Csatár', 'Norvég', 102.00),
(269, 'Jadon Sancho', 10, 'Szélső', 'Angol', 110.00),
(270, 'Marco Reus', 10, 'Támadó középpályás', 'Német', 113.00),
(271, 'Lautaro Martínez', 11, 'Csatár', 'Argentín', 116.00),
(272, 'Milan Škriniar', 11, 'Védő', 'Szlovák', 117.00),
(273, 'Nicolo Barella', 11, 'Középpályás', 'Olasz', 198.00),
(274, 'Joao Félix', 12, 'Szélső', 'Portugál', 191.00),
(275, 'Luis Suárez', 12, 'Csatár', 'Uruguayi', 146.00),
(276, 'Koke', 12, 'Középpályás', 'Spanyol', 157.00),
(277, 'Zlatan Ibrahimović', 13, 'Csatár', 'Svéd', 145.00),
(278, 'Theo Hernández', 13, 'Balhátvéd', 'Francia', 121.00),
(279, 'Franck Kessié', 13, 'Középpályás', 'Elefántcsontparti', 157.00),
(280, 'Bukayo Saka', 14, 'Szélső', 'Angol', 126.00),
(281, 'Pierre-Emerick Aubameyang', 14, 'Csatár', 'Gaboni', 116.00),
(282, 'Thomas Partey', 14, 'Középpályás', 'Ghánai', 178.00),
(283, 'Dusan Tadić', 15, 'Támadó középpályás', 'Szerb', 187.00),
(284, 'Ryan Gravenberch', 15, 'Középpályás', 'Holland', 167.00),
(285, 'Antony', 15, 'Szélső', 'Brazil', 188.00),
(286, 'Christopher Nkunku', 16, 'Támadó középpályás', 'Francia', 123.00),
(287, 'Yussuf Poulsen', 16, 'Csatár', 'Dán', 167.00),
(288, 'Marcel Sabitzer', 16, 'Középpályás', 'Ausztriai', 187.00),
(289, 'Youssef En-Nesyri', 17, 'Csatár', 'Marokkói', 166.00),
(290, 'Jesús Navas', 17, 'Szélső', 'Spanyol', 188.00),
(291, 'Jules Koundé', 17, 'Védő ', 'Francia', 189.00),
(292, 'Lorenzo Insigne', 18, 'Szélső ', 'Olasz', 134.00),
(293, 'Victor Osimhen', 18, 'Csatár', 'Nigeri', 164.00),
(294, 'Kalidou Koulibaly', 18, 'Védő', 'Szenegáli', 124.00),
(295, 'Harry Kane', 19, 'Csatár', 'Angol', 155.00),
(296, 'Son Heung-min', 19, 'Szélső', 'Dél-koreai', 156.00),
(297, 'Pierre-Emile Hojbjerg', 19, 'Középpályás', 'Dán', 112.00),
(298, 'Jordan Veretout', 20, 'Középpályás', 'Francia', 145.00),
(299, 'Tammy Abraham', 20, 'Csatár', 'Angol', 165.00),
(300, 'Leonardo Spinazzola', 20, 'Balhátvéd', 'Olasz', 132.00);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;