--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 01. 22. 13:10:53
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS iskola;

CREATE DATABASE IF NOT EXISTS iskola
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE iskola;

--
-- Create table `tanulok`
--
CREATE TABLE IF NOT EXISTS tanulok (
  nev VARCHAR(255) DEFAULT NULL,
  osztaly VARCHAR(10) DEFAULT NULL,
  szulev INT(11) DEFAULT NULL,
  osztondij DECIMAL(10, 0) DEFAULT NULL,
  atlag DECIMAL(10, 0) DEFAULT NULL,
  neme VARCHAR(10) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table tanulok
--
INSERT INTO tanulok VALUES
('pisti', '10a', 2003, 4500, 4, 'fiú'),
('géza', '10b', 2003, 3500, 5, 'fiú'),
('anna', '10a', 2004, 1500, 3, 'lány'),
('géza', '10a', 2003, 4500, 4, 'fiú'),
('roland', '10b', 2003, 5500, 4, 'fiú'),
('betti', '10a', 2004, 4500, 5, 'lány'),
('gábor', '10a', 2003, 3500, 4, 'fiú'),
('hugó', '10b', 2003, 4500, 4, 'fiú'),
('enikő', '10a', 2004, 2500, 5, 'lány'),
('feri', '10a', 2003, 5500, 3, 'fiú'),
('ágota', '10a', 2003, 2500, 3, 'lány'),
('sanyi', '10a', 2005, 1500, 4, 'fiú'),
('péter', '10b', 2003, 3500, 3, 'fiú'),
('andrea', '10a', 2004, 1500, 5, 'lány');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;