--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 01. 24. 13:24:09
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS csapatok;

CREATE DATABASE IF NOT EXISTS csapatok
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE csapatok;

--
-- Create table `csapatok`
--
CREATE TABLE IF NOT EXISTS csapatok (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  csapat VARCHAR(255) NOT NULL,
  bajnokiCim INT(11) NOT NULL,
  menedzser VARCHAR(255) NOT NULL,
  orszag VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table csapatok
--
INSERT INTO csapatok VALUES
(21, 'RealMadrid', 35, 'Ancelotti', 'Spanyolország'),
(22, 'Barcelona', 27, 'Xavi', 'Spanyolország'),
(23, 'ManchesterUnited', 20, 'tenHag', 'Anglia'),
(24, 'LeicesterCity', 1, 'Marescra', 'Anglia'),
(25, 'Ferencváros', 34, 'Stankovic', 'Magyarország'),
(26, 'AtleticoMadrid', 11, 'Simeone', 'Spanyolország'),
(27, 'Videoton', 3, 'Grzelak', 'Magyarország'),
(28, 'Arsenal', 13, 'Arteta', 'Anglia'),
(29, 'Sevilla', 1, 'Flores', 'Spanyolország'),
(30, 'PSG', 11, 'Enrique', 'Franciaország');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;